### ISSUE TITLE
Add more documentation for builder images

### ISSUE THREAD

**Issue by znmeb** [edgyR/edgyR-containers#35]
There is at least one person using the `internal-ubuntu-builder` image to get a faster RStudio Server on the Apple Silicon Macs via Docker. I hadn't planned on adding user-level documentation for the builders but since there's a user, I probably should.

See https://github.com/rstudio/rstudio/issues/8809#issuecomment-778702395, https://hub.docker.com/r/amoselb/rstudio-m1 and https://github.com/elbamos/rstudio-m1

**Comment by elbamos** [comment]
I didn't need this documentation to build my docker, so if I'm the one person, it isn't necessary.
