### ISSUE TITLE
Specify R version in edgyr/internal-ubuntu-builder

### ISSUE THREAD

**Issue by tyluRp** [edgyR/edgyR-containers#47]
Hello, thanks for putting this together. I am using [`elbamos/rstudio-m1`](https://github.com/elbamos/rstudio-m1) which relies on `edgyr/internal-ubuntu-builder`. This has been the **only** way to get `rstudio-server` running on ARM CPUs without any hassle (at least the only I could find).

Anyways, I was wondering if it's possible to specify the R version in anyway, e.g. `edgyr/internal-ubuntu-builder:4.0.3` for example. My use case is that I am hosting both `rstudio-server` and `shiny-server` on a Raspberry Pi cluster and I want both services running the same version of R.

**Comment by znmeb** [comment]
Now that R 4.1.0 is out I am probably going to refactor this project. The `internal-ubuntu-builder`image will have essentially the same UI as the main image; it'll be usable on any `arm64` Docker host.

Which R versions do you need? My inclination is to do the latest R 3.x, the latest R 4.0 and the latest R 4.1.

**Comment by tyluRp** [comment]
Latest R 4.0.x and 4.1.x would work for me! My main thing is just being able to use a specific tag for a specific version. That or just some documentation on which R version belongs to each image tag.
